import sys
import os
import pytest

sys.path.append(os.path.dirname(sys.path[0]))
from app import app as flask_app


@pytest.fixture()
def app():
    flask_app.config.update(
        {
            "TESTING": True,
        }
    )

    yield flask_app


@pytest.fixture()
def blueleaks_sites():
    return [
        "211sfbay",
        "acprlea",
        "acticaz",
        "akorca",
        "alabamafusioncenter",
        "alabamalecc",
        "alertmidsouth",
        "aorca",
        "arictexas",
        "atlantahidta",
        "attackwa",
        "azhidta",
        "azorca",
        "bostonbric",
        "burlingamepolice",
        "cal-orca",
        "calema",
        "calstas",
        "cbaghidta",
        "ccroc",
        "chicagoheat",
        "chicagolandfsg",
        "ciacco",
        "cnoa3",
        "cnoatraining",
        "cnyorca",
        "coorca",
        "corca",
        "counterdrugtraining",
        "crimestopperslea",
        "cvchidta",
        "dediac",
        "dvicphila",
        "energysecuritycouncil",
        "eousa",
        "fbicahouston",
        "fbinaakansaswmissouri",
        "fbinaamichigan",
        "fbinaatexas",
        "fcpddoc",
        "flinttownshippolice",
        "fwintex",
        "gatlinburglec",
        "graorca",
        "hcsovcp",
        "hennepincountyshield",
        "hidtatraining",
        "hiorca",
        "houstonhidta",
        "houstonhidtatraining",
        "hpdlineup",
        "hpdretired",
        "icefishx",
        "ilcrime",
        "ileatraining",
        "iowaintex",
        "jerseyvillagepd",
        "jric",
        "kcpers",
        "kyorca",
        "lacleartraining",
        "lapdtraining",
        "leapsla",
        "losaltospdbc",
        "lupd",
        "mactf",
        "maorca",
        "membersfaithbased-isao",
        "memiac",
        "metrohoustonpolice",
        "mhidta",
        "miacx",
        "miacxold",
        "millvalleypolice",
        "miorca",
        "mlrin",
        "mnorca",
        "morciu",
        "mtorca",
        "mvpddoc",
        "mvpdtx",
        "ncric-history-good",
        "ncric",
        "ncricSteveBackup",
        "nctccounterdrug",
        "ndslic",
        "nehidta",
        "neorca",
        "nevadacyberexchange",
        "nhiac",
        "njuasi",
        "nmfisoa",
        "nmhidta",
        "nnorca",
        "nnric",
        "northtexasfusion",
        "northtexashidta",
        "novatopolicedept",
        "ntacnv",
        "nvhidta",
        "nymorca",
        "oaklandsheriffshield",
        "oaktac",
        "ociac",
        "okorca",
        "orcaid",
        "orcaor",
        "orocc",
        "otewg",
        "pchidta",
        "phillymostwanted",
        "pleasantonpolice",
        "prvihidta",
        "pspddoc",
        "publicsafetycadets",
        "repo",
        "richlandshield",
        "rlpsaroc",
        "rmhidta",
        "rockhillyorkcountyconnect",
        "ruasi",
        "ruralcountysummit",
        "sacrttac",
        "safecityabq",
        "safecityfw",
        "sanbrunopolice",
        "sccpca",
        "scgcsandiego",
        "sciic",
        "sdciaa",
        "sdfusion",
        "sdorca",
        "sduasi",
        "seattleshield",
        "Securitypartnership",
        "seffc",
        "semacp",
        "sfbay-infragard",
        "sicrime",
        "sltew",
        "snctc",
        "snorca",
        "sogtraining",
        "spottinglies",
        "stopabqgangs",
        "stopeasttexasgangs",
        "stophoustondrugs",
        "stoplubbockgangs",
        "stopnorthtexasgangs",
        "stopsanantoniogangs",
        "stopseattledrugs",
        "stopspokanegangs",
        "stopwesttexasgangs",
        "stxhidta",
        "sunnyvalebriefing",
        "swtxfusion",
        "terrorismtip",
        "texasorca",
        "tnoa",
        "twnsg",
        "unmpd",
        "usao",
        "utahsiac",
        "utorca",
        "vlnsn",
        "vslea",
        "wifusion",
        "wsorca",
    ]


@pytest.fixture()
def client(app):
    return app.test_client()


@pytest.fixture()
def runner(app):
    return app.test_cli_runner()
