name: Deploy to DockerHub
on:
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install pip and poetry
        run: pip install --upgrade pip poetry
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('src/poetry.lock') }}
      - name: Install Poetry dependencies
        run: cd src && poetry install
      - uses: actions/cache@v3
        with:
          path: src/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/frontend/package-lock.json') }}
      - name: Install Node dependencies
        run: cd src/frontend && npm install
      - name: Build frontend
        run: cd src/frontend && npm run build
      - name: Run tests
        run: cd src && poetry run pytest -v

  docker:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: micahflee/blueleaks-explorer:latest
