name: Run tests
on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install pip and poetry
        run: pip install --upgrade pip poetry
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('src/poetry.lock') }}
      - run: cd src && poetry install
      - run: cd src && poetry run pytest -v